#!/bin/sh


#for debugging
#set -ex

# the work tree, where the checkout/deploy should happen
TARGET="reigndes@reignwestry.com:~/public_html/sub_domains/tester3"

# the location of the .git directory
GIT_DIR="reigndes@reignwestry.com:~/public_html/sub_domains/tester3-git-deploy-test.git"


BRANCH="master"

while read oldrev newrev ref
do
        # only checking out the master (or whatever branch you would like to deploy)
        if [ "$ref" = "refs/heads/$BRANCH" ];
        then
                echo "Ref $ref received. Deploying ${BRANCH} branch on server..."
                git --work-tree="${TARGET}" --git-dir="${GIT_DIR}" checkout -f ${BRANCH}

                echo "################################################"
                echo "## PROJECT UPLOADED AND DEPLOYED TO ${BRANCH} ##"
                echo "################################################"
        else
                echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
        fi
done